### ISSUE TITLE
ProteinProphet benchmark not running correctly

### ISSUE THREAD

**Issue by vedran-kasalica** [Workflomics/workflomics-benchmarker#14]
While running Benchmarker on this data: [output_proteinprophet.prot.xml.zip](https://github.com/Workflomics/workflomics-benchmarker/files/15220825/output_proteinprophet.prot.xml.zip) (unzip to get prot.xml) I get the following error

```
return int(benchmark[0])
               ~~~~~~~~~^^^
IndexError: list index out of range
```
referencing [this line](https://github.com/Workflomics/workflomics-benchmarker/blob/bb58af88e54bfaf75804d538d108bf483ff0fc29/src/workflomics_benchmarker/scientific_benchmarks.py#L80)

**Comment by vedran-kasalica** [comment]
It runs when I change `@error=0.01` to `@error=0.001`, but we might need a more flexible solution.

**Comment by magnuspalmblad** [comment]
Yes - I noticed there is only one <error_point> in the table (for @error=0.001), rather than the full table (as from PeptideProphet). When looking carefully, I also see that the errors are not calculated at fixed points (even when they are all there), and the numbers appear to be off. So this is likely a bug in ProteinProphet. But we could also look at the <protein_summary_data_filter> for when the @false_positive_error_rate passes 0.01 and take the @predicted_num_correct at that point (or the maximum value, if it never does).

**Comment by magnuspalmblad** [comment]
This should be more robust, and works when there is a single error point and when there are many (for larger, realistic, datasets):

```
benchmark = root.xpath('//protxml:protein_summary/protxml:protein_summary_header/protxml:program_details/protxml:proteinprophet_details//protxml:error_point[@error<=0.01]/@num_corr', namespaces=namespaces)
print(int(benchmark[len(benchmark)-1]))
```

**Comment by magnuspalmblad** [comment]
Here is an example of a more realistic ProtXML file (and the corresponding PepXML):
[E20232002458a_both.interact.prot.xml.zip](https://github.com/Workflomics/workflomics-benchmarker/files/15221287/E20232002458a_both.interact.prot.xml.zip)
[e20232002458a_both.interact.pep.zip](https://github.com/Workflomics/workflomics-benchmarker/files/15221291/e20232002458a_both.interact.pep.zip)

**Comment by magnuspalmblad** [comment]
But the benchmark computation should obviously be robust (ideally also handle an empty result).

**Comment by vedran-kasalica** [comment]
Thanks for the feedback! I will update the script, and in case of having multiple `false_positive_error_rate` values, do you think it's better to take the smallest or the largest one that's `<=0.01`

**Comment by magnuspalmblad** [comment]
The largest that is <=0.01! At least the table is sorted, so you can take the last element returned by the XPath.

**Comment by magnuspalmblad** [comment]
In my example data, there are actually three points = 0.01. Must correspond to a vertical part of the ROC curve. But the largest would be the most fair benchmark.

**Comment by vedran-kasalica** [comment]
Thank you, I will test it in a bit and update push the updates!
